### ISSUE TITLE
About 1.22 version

### ISSUE THREAD

**Issue by ghost** [Lameguy64/mkpsxiso#10]
After unpacking random game and packing - XA files do not match the original XA. STR files trimmed in the end.

**Comment by Lameguy64** [comment]
What tool are you using to unpack files from a game ISO? Chances are the problems lie on that most likely.

**Comment by Lameguy64** [comment]
I suspect isodump does not extract XA and STR data correctly as with most ISO dumping tools I've used. I've made my own ISO dumping tool that does a much better job at dumping such files and I plan to release it when I find the time.
