### ISSUE TITLE
CD Audio/CUE sheet broken in 1.22

### ISSUE THREAD

**Issue by Lameguy64** [Lameguy64/mkpsxiso#11]
I've recently discovered that CD Audio tracks got broken in 1.22 where such tracks cannot be played properly or at all on a emulator and possibly real hardware.

I'm going to look into this issue and get it fixed when I find the time.

**Comment by Kneesnap** [comment]
Has this been fixed?

**Comment by CookiePLMonster** [comment]
This is probably fixed for a long, long time.
