### ISSUE TITLE
last file syndrome

### ISSUE THREAD

**Issue by 64ghost** [Lameguy64/mkpsxiso#16]
If the last file is a multiple of 2048, then an extra empty sector is added to the image at the end. You can check it through IsoBuster

**Comment by CookiePLMonster** [comment]
I checked this on [my fork](https://github.com/CookiePLMonster/mkpsxiso) and I get identically sized images built if I create a disc with one 2047b file vs a disc with one 2048b file.

**Comment by Lameguy64** [comment]
More or less fixed since the version 2.0 overhaul.
