### ISSUE TITLE
Invalid sectors generated when a license file isn't provided

### ISSUE THREAD

**Issue by spicyjpeg** [Lameguy64/mkpsxiso#24]
When using `mkpsxiso` 2.00 to pack an image without specifying a license file in the XML, the first 37632 (2352x16) bytes of the generated image are zerofilled. This is not the correct behavior as only the payload section of these 16 sectors shall be zerofilled in an image without license data; the 16-byte sector header, as well as the CRC and ECC data at the end of each sector, must still be valid.

Most emulators and tools will reject the image (DuckStation) or fail to detect its format (jPSXdec) if the first sectors are not encoded correctly, *even if the cuesheet lists the first track as `MODE2/2352`*.

**Comment by Lameguy64** [comment]
Fixed in [v2.01](https://github.com/Lameguy64/mkpsxiso/tree/v2.01).
