### ISSUE TITLE
Is the XML file supposed to generate alongside the extracted files?

### ISSUE THREAD

**Issue by wad11656** [Lameguy64/mkpsxiso#27]
I'm extracting "Worms Armageddon" and I'm not seeing any XML files when I run `dumpsxiso` through the Windows binary. I only see the extracted files in the binary's directory. I then ran in Win10-Ubuntu console too, and it output an extra error at the end about not being able to copy track start times or something (but the error was cut off), but I couldn't figure out where it dumped any of the extracted files at all, not to mention the XML file. Can I get help with locating/generating accompanying XML files?

**Comment by CookiePLMonster** [comment]
Aside from specifying the output directory via `-x <path>`, you also need to specify the path to the XML file to create via `-s <path>`.

**Comment by wad11656** [comment]
Wooooo! Amazing! Finally! So many hours of mindless fruitless googling for that flag. I didn't even know about the `-x` flag either. I guess I could've looked at the source code but it's boggling to me that those two flags aren't in the readme

**Comment by CookiePLMonster** [comment]
> Wooooo! Amazing! Finally! So many hours of mindless fruitless googling for that flag.

Or, you could have ran dumpsxiso without arguments to see help, like any competent commandline-based tool does?

```
DUMPSXISO 2.00 - PlayStation ISO dumping tool
2017 Meido-Tek Productions (Lameguy64)
2020 Phoenix (SadNES cITy)
2021-2022 Silent, Chromaryu, G4Vi, and spicyjpeg

dumpsxiso [-h|--help] [-x <path>] [-s <path>] <isofile>

  <isofile>  - File name of ISO file (supports any 2352 byte/sector images).
  -x <path>  - Specified destination directory of extracted files.
  -s <path>  - Outputs an MKPSXISO compatible XML script for later rebuilding.
  -S|--sort-by-dir - Outputs a "pretty" XML script where entries are grouped in directories, instead of strictly following their original order on the disc.
  -e|--encode <codec> - Codec to encode CDDA/DA audio. wave is default. Supported codecs: wave, pcm, flac
  -h|--help  - Show this help text
```

I agree that the readme could have specified it, but your passive aggressiveness is uncalled for since the flag **is** documented.
