### ISSUE TITLE
Merging folders with the same name

### ISSUE THREAD

**Issue by ViToTiV** [Lameguy64/mkpsxiso#28]
XML structure for example:

```
<dir name="ANI">
	<dir name="PAL">
		<file name="RMPBASE.PSX" source="ANI/PAL/RMPBASE.PSX" type="data"/>
		<file name="VRMBASE.PSX" source="ANI/PAL/VRMBASE.PSX" type="data"/>
	</dir>
</dir>
<dir name="PAL">
	<file name="BRIEFIN1.PSR" source="PAL/BRIEFIN1.PSR" type="data"/>
	<file name="BRIEFIN2.PSR" source="PAL/BRIEFIN2.PSR" type="data"/>
</dir>
```

In result image directories "PAL" is merged in "ANI/PAL/" path, and not exist in "PAL/" path

**Comment by Lameguy64** [comment]
Well I couldn't recreate this bug myself. What version of mkpsxiso are you using exactly?

**Comment by ViToTiV** [comment]
On the example of the game "London Racer (Europe)" from redump:
[Original files structure](https://disk.yandex.ru/i/GVs4OsSMitLlOQ)
[Structure after rebuild](https://disk.yandex.ru/i/gpYlagm5yXRu6w)
What I did:
```
1. dumpsxiso.exe -s "London Racer (Europe).xml" "d:\London Racer (Europe)\London Racer (Europe).bin"
2. mkpsxiso.exe "London Racer (Europe).xml"
```
All subfolder "U" is merged to first one (DATA\U\)
And this is not only with this game, but with any game where there are the same folder names in subfolders

**Comment by CookiePLMonster** [comment]
We have this fixed in a fork, yet to be upstreamed: https://github.com/CookiePLMonster/mkpsxiso/commit/9b8445515efba663df798ef037cb31157d85f473

**Comment by CookiePLMonster** [comment]
This is long fixed.
