### ISSUE TITLE
[QUESTION] How to Specify Game ID?

### ISSUE THREAD

**Issue by MediaMaquina** [Lameguy64/mkpsxiso#34]
Hi, is there a way to specify a game ID? Maybe as an identifier?
something like ie: "SLUS-1234"
Thanks!

**Comment by CookiePLMonster** [comment]
ISO9660 discs don't specify a game ID per se AFAIK, If you really need it, you may repurpose any of the current descriptor fields for that.

**Comment by CookiePLMonster** [comment]
9 months with no response, I think it's safe to close. Feel free to reopen if you want to clarify it further.
