### ISSUE TITLE
PSX-EXE LBA and Size

### ISSUE THREAD

**Issue by gledson999** [Lameguy64/mkpsxiso#38]
There are many games that have size and LBA values directly from the PSX-EXE (Executable), would there be a possibility implement that when the ISO is created? So the values would be recalculated internally in PSX-EXE too.

**Comment by CookiePLMonster** [comment]
You can already generate a list of LBAs when building, please see `-help` in `mkpsxiso` for details on how to use it. You have to make use of this data manually though, as automatically patching the executable with new LBAs is effectively impossible.

**Comment by CookiePLMonster** [comment]
I think the stance on this is now clear. If you have any further doubts, feel free to reopen this issue.
