### ISSUE TITLE
str xa file lenght in directory is wrong

### ISSUE THREAD

**Issue by shikeyu** [Lameguy64/mkpsxiso#4]
Original ISO
![image](https://user-images.githubusercontent.com/13993648/41324209-edb1f6ee-6ee5-11e8-9bfc-7aeb11b1d991.png)
Remake ISO
![image](https://user-images.githubusercontent.com/13993648/41324246-23120964-6ee6-11e8-9083-3629020bdb80.png)

I did not change the size of these STR files.
In the PSX ISO, the display size of the STR file in the directory is the LBA number multiplied by 2048.
The actual file size is the LBA number multiplied by 2336.

45636096/2336=19536
19536*2048=40009728

**Comment by Lameguy64** [comment]
Looks to be path table related. Are you using the recently released version of mkpsxiso which fixes the path table encoding.

**Comment by shikeyu** [comment]
I try the 1.19 version. There is no problem now. Thank you.

**Comment by Lameguy64** [comment]
Released 1.20 which includes corrections on the file size calculation for STR and DA type files. See if that has solved one of your remaining issues with mkpsxiso.
