### ISSUE TITLE
v1.19, iso.cpp, Line 323 -- std::string requires assignment

### ISSUE THREAD

**Issue by MeganGrass** [Lameguy64/mkpsxiso#5]
It took me a moment to track down this bug, but basically it was causing invalid ISO file name entries (they would either be blank or a mix of random characters).

For reference, I am using the lastest v1.19 source material and compiling with vs2017 in Windows 10/x64.

I easily fixed it by assigning entry.id:

`entry.id = temp_name;
entry.id.assign(temp_name.c_str());`

...and verified ISO output as working properly.

Thank you for maintaining this application, LameGuy! :)

**Comment by Lameguy64** [comment]
I mainly compiled this program with MinGW GCC as I don't use Microsoft's compilers for my projects. I suppose its due to a slightly different implementation in MS's toolchain but it won't hurt to implement that for the next update.

Thanks for making me aware of that issue.
