### ISSUE TITLE
Build issues on Ubuntu

### ISSUE THREAD

**Issue by itsmattkc** [Lameguy64/mkpsxiso#6]
Building on Ubuntu 16.04 64-bit.

Compiler throws several `error: ‘nullptr’ was not declared in this scope` and `error: ‘std::__cxx11::string {aka class std::__cxx11::basic_string<char>}’ has no member named ‘back’` from several files unless `-std=c++11` is added to the `CXX_FLAGS` (i.e. CMake doesn't add that itself so they have to be manually added to flags.make).

Also throws `error: ‘class tinyxml2::XMLDocument’ has no member named ‘GetErrorLineNum’` for `main.cpp`. [This documentation](http://leethomason.github.io/tinyxml2/classtinyxml2_1_1_x_m_l_document.html) specifies `ErrorLineNum()` instead and changing it to that clears the issue.

After fixing those, mkpsxiso compiles properly.

**Comment by Lameguy64** [comment]
The last issue will be implemented in the next commit. I'm going to have to update tinyxml2 in my setup as I'm still using 4.0.1.
